version: '3'
services:
  prometheus:
    image: prom/prometheus
    #ports:
    #  - '9090:9090'
    container_name: prometheus
    restart: always
    network_mode: host
    volumes:
      - '/home/sigmoid/prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    #ports:
    #  - '3000:3000'
    container_name: grafana
    restart: always
    network_mode: host
    depends_on:
      - prometheus
    volumes:
      - '/home/sigmoid/grafana/grafana-8.3.2/conf/grafana.ini:/etc/grafana/grafana.ini'

