apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: appport
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 8001
      targetPort: 8001